environment:
  SFTP_USERS:
    secretKeyRef:
      name: sftp-secret
      key: combinedcreds
  GCS_CREDENTIALS: # GCP Serviceaccount credentials in a JSON format. (Should only be set if WorkloadIdentity isn't)
    secretKeyRef:
      name: sftp-bucket-credentials
      key: credentials.json

sftp:
  schedule: 0 0 2 * * # CRONJOB Schedule - Once every month on it's second day 
  bucketName: carwiz_jato # Synchronizes files from this bucket

cronjob:
  image:
    repository: google/cloud-sdk
    tag: latest
    pullPolicy: Always
  schedule: "0 0 * * *"
  concurrentPolicy: Forbid # Allow / Forbid / Replace

workloadIdentity: enabled # Please annotate the serviceAccount section incase this is set to `true`

serviceAccount:
  create: true
  annotations: 
    iam.gke.io/gcp-service-account: <KSA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com # Incase workloadIdentity was set to true
  name: ""

volumes:
  storage: 5Gi
  storageClassName: standard

image:
  repository: awakz/sftp-gcloud
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

service:
  type: LoadBalancer
  port: 22

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

