# You'll have to define a username and password in a combined format
# This snippet may be used 
# apiVersion: v1
# kind: Secret
# metadata:
#   name: sftp-secret
# type: Opaque
# stringData:
#   combinedcreds: username:password

environment:
  SFTP_USERS:
    secretKeyRef:
      name: sftp-secret
      key: combinedcreds

# A secret containing GCP serviceaccount with GCS permission in JSON format.
# The following will attach the credentials as a volume to be used for authentication.
# This snippet may be used 
# apiVersion: v1
# kind: Secret
# metadata:
#   name: sftp-bucket-credentials
# type: Opaque
# stringData:
#   credentials.json: |
#     {
#       "type": "service_account",
#       "project_id": "carwiz-97e29",
#       ...
#     }

volumes:
  storage: 5Gi
  storageClassName: standard
  gcsCredentials: sftp-bucket-credentials # Optional - Has to be set incase workloadIdentity: false

workloadIdentity: enabled # Please annotate the serviceAccount section incase this is set to `true`

# To set up Workload Identity, ensure you bind the KSA to the GSA with:
# gcloud iam service-accounts add-iam-policy-binding \
  # <GSA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com
  # --role roles/iam.workloadIdentityUser \
  # --member "serviceAccount:<PROJECT_ID>.svc.id.goog[<NAMESPACE>/<KSA_NAME>]" \
  
serviceAccount:
  create: true
  annotations: 
    # Incase workloadIdentity was set to true
    iam.gke.io/gcp-service-account: <KSA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com
  name: ""

sftp:
  schedule: 0 0 2 * * # CRONJOB Schedule - Once every month on its second day 
  bucketName: carwiz_jato # Files will be downloaded from this bucket

cronjob:
  image:
    repository: google/cloud-sdk
    tag: latest
    pullPolicy: Always
  schedule: "0 0 * * *"
  concurrentPolicy: Forbid # Allow / Forbid / Replace

image:
  repository: awakz/sftp-gcloud
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

service:
  type: LoadBalancer
  port: 22

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

