apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sftp.fullname" . }}-bucket-sync-cronjob
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrentPolicy }} 
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          serviceAccountName: {{ include "sftp.serviceAccountName" . }}
          containers:
          - command:
            - /bin/bash
            - -c
            - |
                # Authenticate && Synchronize GCS files
                {{- if not .Values.workloadIdentity }}
                gcloud auth activate-service-account --key-file /etc/gcp/*.json
                {{- end }}
                gsutil -m rsync -r gs://{{ .Values.sftp.bucketName }} /home/${SFTP_USERS%%:*}/
            image: {{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}
            imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
            name: {{ include "sftp.fullname" . }}-bucket-sync
            env:
              {{- include "sftp.environments" . | nindent 12 }}
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            {{- if not .Values.workloadIdentity }}
            - name: gcp-serviceaccount-credentials
              mountPath: /etc/gcp
              readOnly: true
              {{- end }}
            - name: sftp-data
              mountPath: /home
          volumes:
          {{- if not .Values.workloadIdentity }}
          - name: gcp-serviceaccount-credentials
            secret:
              secretName: {{ .Values.volumes.gcsCredentials }}
            {{- end }}
          - name: sftp-data
            persistentVolumeClaim:
              claimName: sftp-pvc
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: {{ .Values.sftp.schedule }}