apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sftp.fullname" . }}-bucket-sync-cronjob
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrentPolicy }} 
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - |
              POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} --no-headers -o custom-columns=":metadata.name" | grep '^{{ .Chart.Name }}-' | head -n 1)
              kubectl exec $POD_NAME --namespace {{ .Release.Namespace }} -- /bin/bash -c '

                # Authenticate && Synchronize GCS files
                gcloud auth activate-service-account --key-file /etc/gcp/*.json
                gsutil -m rsync -r gs://{{ .Values.sftp.bucketName }} /home/*/
              '
            image: {{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}
            imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
            name: {{ include "sftp.fullname" . }}-bucket-sync
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: {{ .Values.sftp.schedule }}