apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sftp.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
  storageClassName: {{ .Values.volumes.storageClassName }}
